from config import SERVICES_FOLDER
HANDMADE_TAGS={SERVICES_FOLDER+"_3WheeledAudiCarprice_service.wsdl":[],\
               SERVICES_FOLDER+"Academic-degreeFunding.wsdl":[],\
               SERVICES_FOLDER+"CarPriceauto.wsdl":[],\
               SERVICES_FOLDER+"car_pricecolor_service.wsdl":[],\
               SERVICES_FOLDER+"CarPricequality.wsdl":[],\
               SERVICES_FOLDER+"car_pricereport_service.wsdl":[],\
               SERVICES_FOLDER+"CountryDeacon.wsdl":[],\
               SERVICES_FOLDER+"CountryDrought.wsdl":[],\
               SERVICES_FOLDER+"CountryHotel.wsdl":[],\
               SERVICES_FOLDER+"CountryLightning.wsdl":[],\
               SERVICES_FOLDER+"CountryMap.wsdl":[],\
               SERVICES_FOLDER+"FoodPrice1.wsdl":[],\
               SERVICES_FOLDER+"FoodPricephysical-quantity.wsdl":[],\
               SERVICES_FOLDER+"FoodPricequantity.wsdl":[],\
               SERVICES_FOLDER+"FoodPrice.wsdl":[],\
               SERVICES_FOLDER+"FoodRecommendedprice.wsdl":[],\
               SERVICES_FOLDER+"government_funding_BallMissileservice.wsdl":[],\
               SERVICES_FOLDER+"government_funding_ForPhDservice.wsdl":[],\
               SERVICES_FOLDER+"government_funding_Missileservice.wsdl":[],\
               SERVICES_FOLDER+"government_lending_service.wsdl":[]}
