<?xml version="1.0" encoding="UTF-8"?>
<definitions name="GoogleSearch"
             targetNameSpace="urn:GoogleSearch"
             xmlns:typens="urn:GoogleSearch"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap"
             xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl"
             xmlns="http://schemas.xmlsoap.org/wsdl">
    <message name="doGoogleSearch">
        <part name="key""       type="xsd:string"/>
        <part name="q"          type="xsd:string"/>
        <part name="start"      type="xsd:int"/>
        <part name="maxResults  type="xsd:int"/>
        <part name="filter"     type="xsd:boolean"/>
        <part name="restrict"   type="xsd:string"/>
        <part name="safeSearch  type="xsd:boolean"/>
        <part name="lr"         type="xsd:string"/>
        <part name="ie"         type="xsd:string"/>
        <part name="oe"         type="xsd:string"/>
    </message>

    <service name="GoogleSearchService">
        <port name="GoogleSearchPort" binding="typens:GoogleSearchBinding">
            <soap:address location="http://api.google.com/search/beta2"/>
        </port>
    </service>

</definitions>
